### ISSUE TITLE
Blocked Site

### ISSUE THREAD

**Issue by LittleQuartZ** [Cih2001/KodiSubsceneAddon#5]
Is it possible to change "subscene.com" to "subscene.icu" ?

My internet provider blocked subscene.com so i can't use this addon.

**Comment by Cih2001** [comment]
Hi @LittleQuartZ, Sure I can put the domain name in the plugin settings so you can set whatever domain you like. I will do it for you as soon as I get some free time. Which Kodi version are you using? Matrix or Laia?

**Comment by LittleQuartZ** [comment]
Matrix 19.0

**Comment by Cih2001** [comment]
426f2042429963dd9688c27f791549665c149101 is to fix this issue, wait some time and it will be added to the official repo.
